[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=122
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=0
EnableWindow=
MacroID=399dc7f4-9591-4541-9aba-bd5de11f4e2c
Description=LOL全自动1280X720分辨率1.1
Enable=0
AutoRun=0
[Repeat]
Type=1
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]

//LOL全自动1280X720分辨率1.1

//F2视角循环
For 19
//------------------------F2视角------------------------
//寻找对局
MoveTo 601, 685
Delay 100
LeftClick 1
Delay 100

//接受对局
MoveTo 714, 556
Delay 100
LeftClick 1
Delay 100

//赞誉一名队友
Delay 100
LeftClick 1
Delay 100

//升级
Delay 100
LeftClick 1
Delay 100
LeftClick 1

//寻找英雄（第二排最后一个）
Delay 100
MoveTo 910, 277
Delay 100
	LeftClick 1
	Delay 1000
	LeftClick 1
	Delay 200
//（第三排最后一个）
MoveTo 913, 373
Delay 100
LeftClick 1
Delay 100
//寻找英雄（第三排最后一个）
MoveTo 1366, 563
Delay 100
LeftClick 1
Delay 300
//发送邀请
MoveTo 671, 638
Delay 100
LeftClick 1
Delay 100
//锁定英雄
MoveTo 700, 604
Delay 100
LeftClick 1
Delay 500
LeftClick 1
//移动鼠标至中心点
Delay 100
MoveTo 694, 365
Delay 100
//———角色移动———
KeyDown "F2", 1
Delay 100
KeyPress "P", 1
Delay 1000
KeyPress "L", 1
Delay 500
KeyUp "F2", 1
//———角色移动———

//接受对局
MoveTo 714, 556
Delay 100
LeftClick 1
Delay 100

//DF+眼+学习技能+使用技能
KeyDown "Ctrl", 1
KeyPress "R", 1
KeyPress "Q", 1
KeyPress "W", 1
KeyPress "E", 1
KeyUp "Ctrl", 1
Delay 100
KeyPress "4", 1
Delay 100
KeyPress "D", 1
KeyPress "F", 1
Delay 100
KeyPress "R", 1
KeyPress "E", 1
KeyPress "Q", 1
KeyPress "W", 1

//移动鼠标至中心点
MoveTo 938, 581
Delay 100
MoveTo 1045, 549

//———角色移动———
KeyDown "F2", 1
Delay 100
KeyPress "P", 1
Delay 1000
KeyPress "L", 1
Delay 500
KeyUp "F2", 1
//———角色移动———

//移动鼠标至中心点
Delay 100
MoveTo 1045, 549
Delay 100

//———角色移动———
KeyDown "F2", 1
Delay 100
KeyPress "P", 1
Delay 500
KeyPress "L", 1
Delay 100
KeyUp "F2", 1
//———角色移动———
//------------------------F2视角------------------------
Next



//使用表情
Delay 100
KeyPress "T", 1
Delay 100

//F3视角循环
For 19
//------------------------F3视角------------------------
//寻找对局
MoveTo 601, 685
Delay 100
LeftClick 1
Delay 100

//接受对局
MoveTo 714, 556
Delay 100
LeftClick 1
Delay 100

//赞誉一名队友
Delay 100
LeftClick 1
Delay 100

//升级
Delay 100
LeftClick 1
Delay 100
LeftClick 1

//寻找英雄（第二排最后一个）
Delay 100
MoveTo 910, 277
Delay 100
	LeftClick 1
	Delay 1000
	LeftClick 1
	Delay 200
//（第三排最后一个）
MoveTo 913, 373
Delay 100
LeftClick 1
Delay 100
//寻找英雄（第三排最后一个）
MoveTo 1366, 563
Delay 100
LeftClick 1
Delay 300
//发送邀请
MoveTo 671, 638
Delay 100
LeftClick 1
Delay 100
//锁定英雄
MoveTo 700, 604
Delay 100
LeftClick 1
Delay 500
LeftClick 1
//移动鼠标至中心点
Delay 100
MoveTo 694, 365
Delay 100
//———角色移动———
KeyDown "F3", 1
Delay 100
KeyPress "P", 1
Delay 1000
KeyPress "L", 1
Delay 500
KeyUp "F3", 1
//———角色移动———

//接受对局
MoveTo 714, 556
Delay 100
LeftClick 1
Delay 100

//DF+眼+学习技能+使用技能
KeyDown "Ctrl", 1
KeyPress "R", 1
KeyPress "Q", 1
KeyPress "W", 1
KeyPress "E", 1
KeyUp "Ctrl", 1
Delay 100
KeyPress "4", 1
Delay 100
KeyPress "D", 1
KeyPress "F", 1
Delay 100
KeyPress "R", 1
KeyPress "E", 1
KeyPress "Q", 1
KeyPress "W", 1

//移动鼠标至中心点
MoveTo 938, 581
Delay 100
MoveTo 1045, 549

//———角色移动———
KeyDown "F3", 1
Delay 100
KeyPress "P", 1
Delay 1000
KeyPress "L", 1
Delay 500
KeyUp "F3", 1
//———角色移动———

//移动鼠标至中心点
Delay 100
MoveTo 1045, 549
Delay 100

//———角色移动———
KeyDown "F3", 1
Delay 100
KeyPress "P", 1
Delay 500
KeyPress "L", 1
Delay 100
KeyUp "F3", 1
//———角色移动———
//------------------------F3视角------------------------
Next


//使用表情
Delay 100
KeyPress "T", 1
Delay 100

//F4视角循环
For 19
//------------------------F4视角------------------------
//寻找对局
MoveTo 601, 685
Delay 100
LeftClick 1
Delay 100

//接受对局
MoveTo 714, 556
Delay 100
LeftClick 1
Delay 100

//赞誉一名队友
Delay 100
LeftClick 1
Delay 100

//升级
Delay 100
LeftClick 1
Delay 100
LeftClick 1

//寻找英雄（第二排最后一个）
Delay 100
MoveTo 910, 277
Delay 100
	LeftClick 1
	Delay 1000
	LeftClick 1
	Delay 200
//（第三排最后一个）
MoveTo 913, 373
Delay 100
LeftClick 1
Delay 100
//寻找英雄（第三排最后一个）
MoveTo 1366, 563
Delay 100
LeftClick 1
Delay 300
//发送邀请
MoveTo 671, 638
Delay 100
LeftClick 1
Delay 100
//锁定英雄
MoveTo 700, 604
Delay 100
LeftClick 1
Delay 500
LeftClick 1
//移动鼠标至中心点
Delay 100
MoveTo 694, 365
Delay 100
//———角色移动———
KeyDown "F4", 1
Delay 100
KeyPress "P", 1
Delay 1000
KeyPress "L", 1
Delay 500
KeyUp "F4", 1
//———角色移动———

//接受对局
MoveTo 714, 556
Delay 100
LeftClick 1
Delay 100

//DF+眼+学习技能+使用技能
KeyDown "Ctrl", 1
KeyPress "R", 1
KeyPress "Q", 1
KeyPress "W", 1
KeyPress "E", 1
KeyUp "Ctrl", 1
Delay 100
KeyPress "4", 1
Delay 100
KeyPress "D", 1
KeyPress "F", 1
Delay 100
KeyPress "R", 1
KeyPress "E", 1
KeyPress "Q", 1
KeyPress "W", 1

//移动鼠标至中心点
MoveTo 938, 581
Delay 100
MoveTo 1045, 549

//———角色移动———
KeyDown "F4", 1
Delay 100
KeyPress "P", 1
Delay 1000
KeyPress "L", 1
Delay 500
KeyUp "F4", 1
//———角色移动———

//移动鼠标至中心点
Delay 100
MoveTo 1045, 549
Delay 100

//———角色移动———
KeyDown "F4", 1
Delay 100
KeyPress "P", 1
Delay 500
KeyPress "L", 1
Delay 100
KeyUp "F4", 1
//———角色移动———
//------------------------F4视角------------------------
Next



//使用表情
Delay 100
KeyPress "T", 1
Delay 100

//F5视角循环
For 19
//------------------------F5视角------------------------
//寻找对局
MoveTo 601, 685
Delay 100
LeftClick 1
Delay 100

//接受对局
MoveTo 714, 556
Delay 100
LeftClick 1
Delay 100

//赞誉一名队友
Delay 100
LeftClick 1
Delay 100

//升级
Delay 100
LeftClick 1
Delay 100
LeftClick 1

//寻找英雄（第二排最后一个）
Delay 100
MoveTo 910, 277
Delay 100
	LeftClick 1
	Delay 1000
	LeftClick 1
	Delay 200
//（第三排最后一个）
MoveTo 913, 373
Delay 100
LeftClick 1
Delay 100
//寻找英雄（第三排最后一个）
MoveTo 1366, 563
Delay 100
LeftClick 1
Delay 300
//发送邀请
MoveTo 671, 638
Delay 100
LeftClick 1
Delay 100
//锁定英雄
MoveTo 700, 604
Delay 100
LeftClick 1
Delay 500
LeftClick 1
//移动鼠标至中心点
Delay 100
MoveTo 694, 365
Delay 100
//———角色移动———
KeyDown "F5", 1
Delay 100
KeyPress "P", 1
Delay 1000
KeyPress "L", 1
Delay 500
KeyUp "F5", 1
//———角色移动———

//接受对局
MoveTo 714, 556
Delay 100
LeftClick 1
Delay 100

//DF+眼+学习技能+使用技能
KeyDown "Ctrl", 1
KeyPress "R", 1
KeyPress "Q", 1
KeyPress "W", 1
KeyPress "E", 1
KeyUp "Ctrl", 1
Delay 100
KeyPress "4", 1
Delay 100
KeyPress "D", 1
KeyPress "F", 1
Delay 100
KeyPress "R", 1
KeyPress "E", 1
KeyPress "Q", 1
KeyPress "W", 1

//移动鼠标至中心点
MoveTo 938, 581
Delay 100
MoveTo 1045, 549

//———角色移动———
KeyDown "F5", 1
Delay 100
KeyPress "P", 1
Delay 1000
KeyPress "L", 1
Delay 500
KeyUp "F5", 1
//———角色移动———

//移动鼠标至中心点
//Delay 100
//MoveTo 1045, 549
//Delay 100
//锁定英雄错误取消
Delay 100
MoveTo 643, 380
Delay 100
LeftClick 1
Delay 100

//———角色移动———
KeyDown "F5", 1
Delay 100
KeyPress "P", 1
Delay 500
KeyPress "L", 1
Delay 100
KeyUp "F5", 1
//———角色移动———
//------------------------F5视角------------------------
Next


//使用表情
Delay 100
KeyPress "T", 1
Delay 100
